import java.awt.Color;
import java.io.File;
import java.util.Arrays;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARTHUR
 */

public class telaPrincipal extends javax.swing.JFrame {
    
    int busca, contador = 0, j = 0;
    int[] vetor = new int[26];
    GloboDaSorte globo = new GloboDaSorte(1, 26);
    String caminho;
    
    final JFXPanel fxPanel = new JFXPanel();

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();        
    }
    
    public String letra(int numero) {
    switch (numero) {
        case 1:
            txtLetra.setText("A");
            lblA.setForeground(Color.red);
            caminho = "A.mp3";
            break;
        case 2:
            txtLetra.setText("B");
            lblB.setForeground(Color.red);
            caminho = "B.mp3";
            break;
        case 3:
            txtLetra.setText("C");
            lblC.setForeground(Color.red);
            caminho = "C.mp3";
            break;
        case 4:
            txtLetra.setText("D");
            lblD.setForeground(Color.red);
            caminho = "D.mp3";
            break;
        case 5:
            txtLetra.setText("E");
            lblE.setForeground(Color.red);
            caminho = "E.mp3";
            break;
        case 6:
            txtLetra.setText("F");
            lblF.setForeground(Color.red);
            caminho = "F.mp3";
            break;
        case 7:
            txtLetra.setText("G");
            lblG.setForeground(Color.red);
            caminho = "G.mp3";
            break;
        case 8:
            txtLetra.setText("H");
            lblH.setForeground(Color.red);
            caminho = "H.mp3";
            break;
        case 9:
            txtLetra.setText("I");
            lblI.setForeground(Color.red);
            caminho = "I.mp3";
            break;
        case 10:
            txtLetra.setText("J");
            lblJ.setForeground(Color.red);
            caminho = "J.mp3";
            break;
        case 11:
            txtLetra.setText("K");
            lblK.setForeground(Color.red);
            caminho = "K.mp3";
            break;
        case 12:
            txtLetra.setText("L");
            lblL.setForeground(Color.red);
            caminho = "L.mp3";
            break;
        case 13:
            txtLetra.setText("M");
            lblM.setForeground(Color.red);
            caminho = "M.mp3";
            break;
        case 14:
            txtLetra.setText("N");
            lblN.setForeground(Color.red);
            caminho = "N.mp3";
            break;
        case 15:
            txtLetra.setText("O");
            lblO.setForeground(Color.red);
            caminho = "O.mp3";
            break;
        case 16:
            txtLetra.setText("P");
            lblP.setForeground(Color.red);
            caminho = "P.mp3";
            break;
        case 17:
            txtLetra.setText("Q");
            lblQ.setForeground(Color.red);
            caminho = "Q.mp3";
            break;
        case 18:
            txtLetra.setText("R");
            lblR.setForeground(Color.red);
            caminho = "R.mp3";
            break;
        case 19:
            txtLetra.setText("S");
            lblS.setForeground(Color.red);
            caminho = "S.mp3";
            break;
        case 20:
            txtLetra.setText("T");
            lblT.setForeground(Color.red);
            caminho = "T.mp3";
            break;
        case 21:
            txtLetra.setText("U");
            lblU.setForeground(Color.red);
            caminho = "U.mp3";
            break;
        case 22:
            txtLetra.setText("V");
            lblV.setForeground(Color.red);
            caminho = "V.mp3";
            break;
        case 23:
            txtLetra.setText("W");
            lblW.setForeground(Color.red);
            caminho = "W.mp3";
            break;
        case 24:
            txtLetra.setText("X");
            lblX.setForeground(Color.red);
            caminho = "X.mp3";
            break;
        case 25:
            txtLetra.setText("Y");
            lblY.setForeground(Color.red);
            caminho = "Y.mp3";
            break;
        case 26:
            txtLetra.setText("Z");
            lblZ.setForeground(Color.red);
            caminho = "Z.mp3";
            break;
        }
        return null;
    }
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSortear = new javax.swing.JButton();
        txtLetra = new javax.swing.JTextField();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblJ = new javax.swing.JLabel();
        lblK = new javax.swing.JLabel();
        lblL = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        lblR = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        lblV = new javax.swing.JLabel();
        lblW = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblZ = new javax.swing.JLabel();
        btnRecomecar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSortear.setText("Sortear Letra");
        btnSortear.setName(""); // NOI18N
        btnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearActionPerformed(evt);
            }
        });

        txtLetra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLetra.setEnabled(false);

        lblA.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblA.setText("A");

        lblB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblB.setText("B");

        lblC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblC.setText("C");

        lblD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblD.setText("D");

        lblE.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblE.setText("E");

        lblF.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblF.setText("F");

        lblG.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblG.setText("G");

        lblH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblH.setText("H");

        lblI.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblI.setText("I");

        lblJ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblJ.setText("J");

        lblK.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblK.setText("K");

        lblL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblL.setText("L");

        lblM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblM.setText("M");

        lblN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblN.setText("N");

        lblO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblO.setText("O");

        lblP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblP.setText("P");

        lblQ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblQ.setText("Q");

        lblR.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblR.setText("R");

        lblS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblS.setText("S");

        lblT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblT.setText("T");

        lblU.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblU.setText("U");

        lblV.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblV.setText("V");

        lblW.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblW.setText("W");

        lblX.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblX.setText("X");

        lblY.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblY.setText("Y");

        lblZ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblZ.setText("Z");

        btnRecomecar.setText("Recomeçar");
        btnRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomecarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRecomecar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblG)
                                    .addComponent(lblM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblH)
                                    .addComponent(lblN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblO)
                                    .addComponent(lblI, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblP)
                                    .addComponent(lblJ))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblK)
                                .addGap(18, 18, 18)
                                .addComponent(lblL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblR))
                            .addComponent(lblF)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZ)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLetra, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btnSortear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRecomecar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(lblB)
                    .addComponent(lblC)
                    .addComponent(lblE)
                    .addComponent(lblF)
                    .addComponent(lblD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblG)
                    .addComponent(lblH)
                    .addComponent(lblI)
                    .addComponent(lblJ)
                    .addComponent(lblK)
                    .addComponent(lblL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblM)
                    .addComponent(lblN)
                    .addComponent(lblO)
                    .addComponent(lblP)
                    .addComponent(lblQ)
                    .addComponent(lblR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS)
                    .addComponent(lblT)
                    .addComponent(lblU)
                    .addComponent(lblV)
                    .addComponent(lblW)
                    .addComponent(lblX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblY)
                    .addComponent(lblZ))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
        // TODO add your handling code here: 
        if (j > 25) {
            txtLetra.setText("ACABOU!");
            btnSortear.setEnabled(false);
        } else {
            vetor[j] = globo.sortear();
            System.out.println(vetor[j]);
            letra(vetor[j]);
            
            String uriString = new File("C:\\Users\\ARTHUR\\Documents\\GitHub\\Bingo-de-Letras-Java\\musics\\" + caminho).toURI().toString();
            Media pick = new Media(uriString); 
            MediaPlayer player = new MediaPlayer(pick); 
            player.play();
            j++;
        }
    }//GEN-LAST:event_btnSortearActionPerformed

    private void btnRecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomecarActionPerformed
        // TODO add your handling code here:
        btnSortear.setEnabled(true);
        txtLetra.setText("");
        Arrays.fill(vetor, 0);
        globo = new GloboDaSorte(1, 26);
        j = 0;
        lblA.setForeground(Color.black);
        lblB.setForeground(Color.black);
        lblC.setForeground(Color.black);
        lblD.setForeground(Color.black);
        lblE.setForeground(Color.black);
        lblF.setForeground(Color.black);
        lblG.setForeground(Color.black);
        lblH.setForeground(Color.black);
        lblI.setForeground(Color.black);
        lblJ.setForeground(Color.black);
        lblK.setForeground(Color.black);
        lblL.setForeground(Color.black);
        lblM.setForeground(Color.black);
        lblN.setForeground(Color.black);
        lblO.setForeground(Color.black);
        lblP.setForeground(Color.black);
        lblQ.setForeground(Color.black);
        lblR.setForeground(Color.black);
        lblS.setForeground(Color.black);
        lblT.setForeground(Color.black);
        lblU.setForeground(Color.black);
        lblV.setForeground(Color.black);
        lblW.setForeground(Color.black);
        lblX.setForeground(Color.black);
        lblY.setForeground(Color.black);
        lblZ.setForeground(Color.black);
    }//GEN-LAST:event_btnRecomecarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecomecar;
    private javax.swing.JButton btnSortear;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblJ;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblV;
    private javax.swing.JLabel lblW;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblZ;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
